export const menus = [
  { text: '首页', path: '/'},
  { text: '代练', path: ''},
  { text: '帐号', path: ''},
  { text: '装备', path: ''},
  { text: '首充号', path: ''},
  { text: '游戏币', path: ''},
  { text: '游戏资讯', path: ''},
  { text: '排行榜', path: ''},
  { text: '游戏下载', path: ''},
  { text: '游戏圈', path: ''},
];

export const personalMenus = [
  { text: '个人中心', path: './'},
  { text: '消息中心', path: 'messages'},
  { text: '资金明细', path: 'finance'},
  { text: '个人信息', path: 'info'},
  { text: 'divider' },
  { text: '我要买', path: '/buy'},
  { text: '已买到的商品', path: 'purchased'},
  { text: '关注的商品', path: 'liked'},
  { text: 'divider' },
  { text: '我要卖', path: '/sale'},
  { text: '出售中的商品', path: 'on-sale'},
  { text: '已售出的商品', path: 'sold'},
  { text: 'divider' },
  { text: '帐号安全', path: 'security'},
  { text: '投诉管理', path: 'complaint'},
  { text: '反馈信息', path: 'feedback'},
  { text: '注销登录'},
];
